- name: Set fs.inotify.max_user_watches in sysctl
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '{{ vscode_max_watches }}'

- name: Task wsl
  ansible.builtin.include_tasks:
    file: wsl.yml
  when: ansible_facts.virtualization_type == "wsl"
