# config
#   modify *.cnf
---
- name: Task dict on os for mariadb_config_files
  ansible.builtin.include_role:
    name: os
    tasks_from: dict
  vars:
    os_dict_os: '{{ mariadb_config_files_os }}'
  when: mariadb_config_files is not defined

- name: Set mariadb_config_files from os_dict
  ansible.builtin.set_fact:
    mariadb_config_files: '{{ os_dict }}'
  when: mariadb_config_files is not defined

- name: Modify mariadb client config file
  become: true
  community.general.ini_file:
    create: false
    path: '{{ mariadb_config_files.client }}'
    section: client
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: >-
    {{
      {"default-character-set": mariadb_config_charset}
      | combine(mariadb_config_client)
      | dict2items
    }}

- name: Modify mariadb server config file
  become: true
  community.general.ini_file:
    create: false
    path: '{{ mariadb_config_files.server }}'
    section: server
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: >-
    {{
      {"character-set-server": mariadb_config_charset, "collation-server": mariadb_config_collation}
      | combine(mariadb_config_server)
      | dict2items
    }}
  notify: mariadb_restart_mariadb
