- name: Set mariadb_install_name is empty string when apt
  ansible.builtin.set_fact:
    mariadb_install_name: ''
  when:
    - mariadb_source == "pkg"
    - ansible_facts.pkg_mgr == "apt"

- name: Set mariadb_install_pkgs
  ansible.builtin.set_fact:
    mariadb_install_pkgs: '{{ mariadb_libs | map("regex_replace", "^", mariadb_name ~ "-") }}'
  when: mariadb_source == "pkg"

- name: Add packages to mariadb_install_pkgs when apt
  ansible.builtin.set_fact:
    mariadb_install_pkgs: '{{ mariadb_install_pkgs | union([mariadb_name ~ "-client", mariadb_name ~ "-server"]) }}'
  when:
    - mariadb_source == "pkg"
    - ansible_facts.pkg_mgr == "apt"

- name: Add packages to mariadb_install_pkgs when dnf
  ansible.builtin.set_fact:
    mariadb_install_pkgs: '{{ mariadb_install_pkgs | union([mariadb_name ~ "-server"]) }}'
  when:
    - mariadb_source == "pkg"
    - ansible_facts.pkg_mgr == "dnf"

- name: Add devel package to mariadb_install_pkgs when apt
  ansible.builtin.set_fact:
    mariadb_install_pkgs: '{{ mariadb_install_pkgs | union(["lib" ~ mariadb_name ~ "-dev"]) }}'
  when:
    - mariadb_source == "pkg"
    - ansible_facts.pkg_mgr == "apt"
    - mariadb_devel

- name: Add devel package to mariadb_install_pkgs when dnf
  ansible.builtin.set_fact:
    mariadb_install_pkgs: '{{ mariadb_install_pkgs | union([mariadb_name ~ "-connector-c-devel"]) }}'
  when:
    - mariadb_source == "pkg"
    - ansible_facts.pkg_mgr == "dnf"
    - mariadb_devel

- name: Task install on app for mariadb
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ mariadb_install_name | default(mariadb_name) }}'
      version: '{{ mariadb_version }}'
      source: '{{ mariadb_source }}'
      pkgs: '{{ mariadb_install_pkgs | default([]) }}'

- name: Task list on os for mariadb_control_pkgs
  ansible.builtin.include_role:
    name: os
    tasks_from: list
  vars:
    os_list_os: '{{ mariadb_control_pkgs_os }}'

- name: Set mariadb_control_pkgs from os_list
  ansible.builtin.set_fact:
    mariadb_control_pkgs: '{{ os_list }}'

- name: Task install on app to control mariadb
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      pkgs: '{{ mariadb_control_pkgs }}'
