- name: Start and enable mariadb service
  become: true
  ansible.builtin.service:
    name: '{{ mariadb_service_name }}'
    state: started
    enabled: true
  when: mariadb_service

- name: Stop and disbale mariadb service
  become: true
  ansible.builtin.service:
    name: '{{ mariadb_service_name }}'
    state: stopped
    enabled: false
  when: not mariadb_service
