- name: Set no password for root user
  become: true
  community.mysql.mysql_query:
    login_unix_socket: '{{ mariadb.socket }}'
    login_user: root
    query:
      - ALTER USER 'root'@'localhost' IDENTIFIED BY '';
      - FLUSH PRIVILEGES;

- name: Create admin user
  become: true
  community.mysql.mysql_user:
    login_unix_socket: '{{ mariadb.socket }}'
    login_user: root
    state: present
    name: '{{ mariadb.admin.name }}'
    host: localhost
    password: '{{ mariadb.admin.password }}'
    priv: '*.*:ALL'

- name: Create ansible user
  become: true
  community.mysql.mysql_user:
    login_unix_socket: '{{ mariadb.socket }}'
    login_user: root
    state: present
    name: '{{ ansible_user }}'
    host: localhost
    priv: '*.*:ALL'
