- name: Install epel-release
  become: true
  ansible.builtin.dnf:
    name: epel-release
  when: ansible_facts.os_family == "RedHat"

- name: Install snapd
  become: true
  ansible.builtin.package:
    name: snapd
