- name: Start and enable snapd service
  become: true
  ansible.builtin.service:
    name: snapd
    state: started
    enabled: true
  when: snap_auto

- name: Stop and disbale snapd service
  become: true
  ansible.builtin.service:
    name: snapd
    state: stopped
    enabled: false
  when: not snap_auto
