require_relative "../common"

Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/rocky-9"

  # if you want to extend disk size, you can use (defaut size 32GB):
  # expand_disk(config)

  common_config(config)
end
