# time
---
- name: 'Set RTC to {{ time_rtc_local | ternary("local", "UTC") }}'
  become: true
  ansible.builtin.command:
    argv:
      - timedatectl
      - set-local-rtc
      - '{{ time_rtc_local | ternary("1", "0") }}'
  changed_when: true
  when: ansible_facts.service_mgr == "systemd"

# FIXME: RedHat系でタイムゾーンを変更するときに、SELinuxの許可モードに変更する必要がある。
- name: Change permissive mode for SELinux
  become: true
  ansible.posix.selinux:
    policy: '{{ ansible_facts.selinux.targeted }}'
    state: permissive
  notify: system_enforce_selinux
  when:
    - ansible_facts.selinux is defined
    - ansible_facts.selinux.status == "enabled"
    - ansible_facts.selinux.mode == "enforcing"

- name: Set timezone
  become: true
  community.general.timezone:
    name: '{{ time_timezone }}'
