AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Metrics double

Metrics/AbcSize:
  Max: 30 # 15

Metrics/BlockLength:
  Max: 50 # 25
  CountAsOne:
    - array
    - hash
    - heredoc
  AllowedMethods:
    - refine
    - configure

Metrics/BlockNesting:
  Max: 6 # 3

Metrics/ClassLength:
  Max: 200 # 100
  Exclude:
    - test/**/*.rb
    - app/controllers/*.rb

Metrics/CyclomaticComplexity:
  Max: 12 # 6

Metrics/MethodLength:
  Max: 20 # 10
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - db/migrate/*.rb

Metrics/ModuleLength:
  Max: 200 # 100

Metrics/ParameterLists:
  Max: 10 # 5
  MaxOptionalParameters: 6 # 3

Metrics/PerceivedComplexity:
  Max: 14 # 7

Naming/AccessorMethodName:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/OneLineConditional:
  AlwaysCorrectToMultiline: true

Style/PerlBackrefs:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets
