- name: 'Task repo_{{ ansible_facts.pkg_mgr }}'
  ansible.builtin.include_tasks:
    file: repo_{{ ansible_facts.pkg_mgr }}.yml

- name: Task install on app for vagrant
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: vagrant
