# Vagrant
---
- name: Task install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Task wsl
  ansible.builtin.include_tasks:
    file: wsl.yml
  when: >-
    ansible_facts.virtualization_type == "wsl" or
    ansible_facts.service_mgr == "init(" ~ ansible_facts.user_id ~ ")"
