# https://developer.hashicorp.com/vagrant/install
- name: Task repo on apt for vagrant
  ansible.builtin.import_role:
    name: apt
    tasks_from: repo
  vars:
    apt_repo:
      name: hashicorp
      url: https://apt.releases.hashicorp.com
      component: main
      gpg: https://apt.releases.hashicorp.com/gpg
