- name: Install Font package by apt
  become: true
  ansible.builtin.apt:
    name: '{{ font_fonts | map("regex_replace", "^", "fonts-") }}'
  when:
    - font_fonts | length > 0
    - ansible_pkg_mgr == "apt"

- name: Install Font package by dnf
  become: true
  ansible.builtin.dnf:
    name: '{{ font_fonts | map("regex_replace", "$", "-fonts") }}'
  when:
    - font_fonts | length > 0
    - ansible_pkg_mgr == "apt"

- name: Make /etc/fonts diretory
  become: true
  ansible.builtin.file:
    path: /etc/fonts
    owner: root
    group: root
    mode: '0755'
  when: font_windows

- name: Copy fonts/local.conf
  become: true
  ansible.builtin.copy:
    src: fonts/local.conf
    dest: /etc/fonts/local.conf
    owner: root
    group: root
    mode: '0644'
  when: font_windows
