user_name: "root" # must overide
# user_password: ""
user_group: '{{ user_name }}'
user_groups:
  - adm
  - wheel
  - sudo
  - users
user_shell: /bin/bash
# user_home: '/home/{{ user_name }}'
# user_comment: ""
user_sudo_without_password: false
