# epel
- name: Install epel repository
  become: true
  ansible.builtin.dnf:
    state: present
    name: epel-release

# cloudsmith

- name: Install isc-kea repository
  ansible.builtin.shell:
    cmd: |
      curl -1sLf \
        'https://dl.cloudsmith.io/public/isc/kea-2-6/setup.rpm.sh' \
       | sudo -E bash
    creates: /etc/yum.repos.d/isc-kea-2-6.repo

- name: Install kea
  become: yes
  ansible.builtin.dnf:
    pkg:
      - isc-kea
      - isc-kea-hooks

- name: Create kea db
  become: yes
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: '{{ item }}'
  loop:
    - kea
    - kea_development
    - kea_test

- name: Create kea user
  become: yes
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: kea
    host: localhost
    password: keapass
    priv: 'kea.*:ALL/kea_development.*:ALL/kea_test.*:ALL'

- name: Run kea-admin init
  become: yes
  ansible.builtin.command:
    argv: 
      - kea-admin
      - db-init
      - mysql
      - -u
      - kea
      - -p
      - keapass
      - -n
      - '{{ item }}'
  loop:
    - kea
    - kea_development
    - kea_test

# - name: 'kea-admin upgrade {{ item }}'
#   become: yes
#   command:
#     cmd: 'kea-admin db-upgrade mysql -u kea -p keapass -n {{ item }}'
#   when: 'item in mysql_info_result.databases'
