- name: 'Task repo_{{ ansible_pkg_mgr }}'
  ansible.builtin.include_tasks:
    file: repo_{{ ansible_pkg_mgr }}.yml

- name: Install vagrant
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
