- name: 'Task repo_{{ ansible_facts.pkg_mgr }}'
  ansible.builtin.include_tasks:
    file: repo_{{ ansible_facts.pkg_mgr }}.yml

- name: Task install on app for docker
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      pkgs:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
