- name: Assert systemd
  ansible.builtin.assert:
    that: ansible_facts.service_mgr == "systemd"
    msg: "require systemd, but ansible_facts.service_mgr is {{ ansible_facts.service_mgr }}"
    quiet: true

- name: Task install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Task config
  ansible.builtin.import_tasks:
    file: config.yml

- name: Task serivce
  ansible.builtin.import_tasks:
    file: service.yml
  when: ansible_facts.service_mgr == "systemd"

- name: Task user
  ansible.builtin.import_tasks:
    file: user.yml
