- name: Task install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Task config
  ansible.builtin.import_tasks:
    file: config.yml

- name: Add default user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true
