# https://developer.hashicorp.com/vagrant/install

- name: Assert ansible_facts.pkg_mgr is dnf
  ansible.builtin.assert:
    that: ansible_facts.pkg_mgr == "dnf"
    msg: "ansible_facts.pkg_mgr is not dnf, but {{ ansible_facts.pkg_mgr }}"
    quiet: true

# TODO: まだ書いていない
- name: Not supported dnf
  ansible.builtin.fail:
    msg: not support
