# https://developer.hashicorp.com/vagrant/install

- name: Assert ansible_facts.pkg_mgr is dnf
  ansible.builtin.assert:
    that: ansible_facts.pkg_mgr == "dnf"
    msg: "ansible_facts.pkg_mgr is not dnf, but {{ ansible_facts.pkg_mgr }}"
    quiet: true

- name: Task repo on dnf for docker
  ansible.builtin.import_role:
    name: dnf
    tasks_from: repo
  vars:
    dnf_repo:
      url: https://download.docker.com/linux/rhel/docker-ce.repo
      gpg: https://download.docker.com/linux/rhel/gpg
