# https://docs.docker.com/engine/install/ubuntu/
- name: Task repo on apt for docker
  ansible.builtin.import_role:
    name: apt
    tasks_from: repo
  vars:
    apt_repo:
      name: docker
      url: https://download.docker.com/linux/ubuntu
      component: stable
      gpg: https://download.docker.com/linux/ubuntu/gpg
