- name: Start and enable docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: docker_auto

- name: Stop and disbale docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: stopped
    enabled: false
  when: not docker_auto
