- name: Start and enable nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: docker_auto

- name: Stop and disbale nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: stopped
    enabled: false
  when: not docker_auto
