- name: Restart docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
  when:
    - ansible_facts.service_mgr == "systemd"
    - docker_auto
  listen: docker_restart_docker
