- name: Restart nginx service
  become: true
  ansible.builtin.service:
    name: '{{ nginx_service_name }}'
    state: restarted
  when:
    - ansible_facts.service_mgr == "systemd"
    - nginx_service_auto
  listen: nginx_restart_nginx
