- name: Install language package for Ubuntu
  become: true
  ansible.builtin.apt:
    name: 'language-pack-{{ lang_package }}'
  when: ansible_facts.distribution == "Ubuntu"

- name: Install language package for Debian
  become: true
  ansible.builtin.apt:
    name: 'locales-all'
  when: ansible_facts.distribution == "Deiban"

- name: Install language package for RedHat family
  become: true
  ansible.builtin.dnf:
    name: 'langpacks-{{ lang_package }}'
  when: ansible_facts.os_family == "RedHat"

# FIXME: もしかしたらUbuntuでも必要ない？
- name: Create locale when apt only
  become: true
  community.general.locale_gen:
    name: '{{ lang_locale }}'
  when:
    - ansible_facts.service_mgr == "systemd"
    - ansible_facts.os_family == "Debian"

# FIMXE: Debianでは動かない？update-localeを使う必要がある。
- name: Set locale
  become: true
  ansible.builtin.command:
    argv:
      - localectl
      - set-locale
      - '{{ lang_locale }}'
  changed_when: true
  when:
    - ansible_facts.service_mgr == "systemd"
    - ansible_facts.distribution != "Debian"

- name: Set locale for Debian
  become: true
  ansible.builtin.command:
    argv:
      - update-locale
      - 'LANG={{ lang_locale }}'
  changed_when: true
  when: ansible_facts.distribution == "Debian"

# TODO: manpageはどうするのか？
# # FIXME: dnfは日本語manが無い？
# - name: Install manual packages
#   become: true
#   ansible.builtin.apt:
#     name:
#       - 'manpages-{{ lang_package }}'
#       - 'manpages-{{ lang_package }}-dev'
#   when: ansible_facts.pkg_mgr == "apt"
