# TODO: Debianにはlanguage-pack-jaがない可能性がある。代わりにlocales-allを入れる必要があるかも。
- name: Install language package by apt
  become: true
  ansible.builtin.apt:
    name: 'language-pack-{{ lang_package }}'
  when: ansible_pkg_mgr == "apt"

- name: Install language package by dnf
  become: true
  ansible.builtin.dnf:
    name: 'langpacks-{{ lang_package }}'
  when: ansible_pkg_mgr == "dnf"

- name: Create locale
  become: true
  community.general.locale_gen:
    name: '{{ lang_locale }}'
  when: system_init == "systemd"

- name: Set locale
  become: true
  ansible.builtin.command:
    argv:
      - localectl
      - set-locale
      - '{{ lang_locale }}'
  changed_when: true
  when: system_init == "systemd"

# TODO: manpageはどうするのか？
# # FIXME: dnfは日本語manが無い？
# - name: Install manual packages
#   become: true
#   ansible.builtin.apt:
#     name:
#       - 'manpages-{{ lang_package }}'
#       - 'manpages-{{ lang_package }}-dev'
#   when: ansible_pkg_mgr == "apt"
