- name: Get npm config prefix
  ansible.builtin.command:
    cmd: npm config get prefix
  register: nodejs_config_npm_prefix
  changed_when: false
  when: nodejs_source == "pkg"

- name: Set npm config prefix
  ansible.builtin.command:
    cmd: npm config set prefix=~/.local
  changed_when: true
  when:
    - nodejs_source == "pkg"
    - nodejs_config_npm_prefix.stdout | trim == "/usr/local"

- name: Set npm config cafile for mise
  ansible.builtin.shell:
    cmd: |
      {{ mise_shell_block }}
      npm config set cafile {{ cert_ca_file }}
    executable: /bin/bash
  changed_when: true
  when:
    - nodejs_source == "mise"
    - cert_trusted_cas != {}
