- name: Get npm config prefix
  ansible.builtin.command:
    cmd: npm config get prefix
  register: nodejs_config_npm_prefix
  changed_when: false
  when: nodejs_pkg_mgr != "bun"

- name: Set npm config prefix
  ansible.builtin.command:
    cmd: npm config set prefix=~/.local
  changed_when: true
  when:
    - nodejs_pkg_mgr != "bun"
    - nodejs_config_npm_prefix.stdout | trim == "/usr/local"

- name: Block nodejs in bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK nodejs'
    block: |
      {% for key, value in nodejs_env.items() %}
      export {{ key }}={{ value }}
      {% endfor %}
  when: nodejs_env != {}
