- name: Task install on app for nodejs dependent packages
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      pkgs: '{{ nodejs_dep_pkgs }}'
  when: nodejs_dep_pkgs != []

- name: Set nodejs_install_pkgs
  ansible.builtin.set_fact:
    nodejs_install_pkgs: '{{ nodejs_libs | map("regex_replace", "^", nodejs_name ~ "-") }}'
  when: nodejs_source == "pkg"

- name: Add packages to nodejs_install_pkgs
  ansible.builtin.set_fact:
    nodejs_install_pkgs: '{{ nodejs_install_pkgs | union(["npm"]) }}'
  when:
    - nodejs_source == "pkg"
    - nodejs_pkg_mgr in ["npm", "yarn", "pnpm"]

- name: Task install on app for nodejs
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ nodejs_name }}'
      version: '{{ nodejs_version }}'
      source: '{{ nodejs_source }}'
      devel: '{{ nodejs_devel }}'
      pkgs: '{{ nodejs_install_pkgs | default([]) }}'
