- name: Task install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Task config
  ansible.builtin.import_tasks:
    file: config.yml

- name: Task pkg_mgr
  ansible.builtin.import_tasks:
    file: pkg_mgr.yml

- name: Task npm
  ansible.builtin.import_tasks:
    file: npm.yml
