require_relative "../common"

Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9" # 20GB
  # config.vm.box = "eurolinux-vagrant/almalinux-9"
  # config.vm.box = "bento/almalinux-9" # with chef
  # config.vm.box = "generic/alma9" # not active
  # config.vm.box = "openlogic/almalinux-9" # not active

  # if you want to extend disk size, you can use (defaut size 32GB):
  expand_disk(config)

  common_config(config)
end
