- name: Task install on app for ruby
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: ruby
      ver: '{{ ruby_ver }}'
      src: '{{ ruby_src }}'
      dev: '{{ ruby_dev }}'
      pkgs: '{{ ruby_libs | map("regex_replace", "^", "ruby-") }}'
