# freeradius-mysql は CRB
- name: Enable crb repo
  become: yes
  community.general.dnf_config_manager:
    name: crb

- name: Install freeradius
  become: yes
  ansible.builtin.dnf:
    pkg:
      - freeradius
      - freeradius-mysql
      - freeradius-ldap

- name: Create radius db
  become: yes
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: '{{ item }}'
  loop:
    - radius
    - radius_development
    - radius_test

- name: Create radius user
  become: yes
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: radius
    host: localhost
    password: radpass
    priv: 'radius.*:ALL/radius_development.*:ALL/radius_test.*:ALL'

- name: Run mysql scheme.sql
  become: yes
  ansible.builtin.shell:
    cmd: 'mysql -u root {{ item }} < /etc/raddb/mods-config/sql/main/mysql/schema.sql'
  loop:
    - radius
    - radius_development
    - radius_test
