mariadb_config_files_os:
  RedHat:
    client: /etc/my.cnf.d/client.cnf
    server: /etc/my.cnf.d/mariadb-server.cnf
  Debian:
    client: /etc/mysql/mariadb.conf.d/50-client.cnf
    server: /etc/mysql/mariadb.conf.d/50-server.cnf
mariadb_server_socket_os:
  Debian: /run/mysqld/mysqld.sock
  RedHat: /var/lib/mysql/mysql.sock
mariadb_control_pkgs_os:
  Debian:
    - python3-pymysql
  RedHat:
    - python3-PyMySQL
