mariadb_files:
  RedHat:
    7:
      socket: /var/lib/mysql/mysql.sock
      client_cnf: /etc/my.cnf.d/client.cnf
      server_cnf: /etc/my.cnf.d/server.cnf
    8:
      socket: /var/lib/mysql/mysql.sock
      client_cnf: /etc/my.cnf.d/client.cnf
      server_cnf: /etc/my.cnf.d/mariadb-server.cnf
    9:
    10:
  Debian:
  yum:
    socket: /var/lib/mysql/mysql.sock
    client_cnf: /etc/my.cnf.d/client.cnf
    server_cnf: /etc/my.cnf.d/server.cnf
  dnf:
    socket: /var/lib/mysql/mysql.sock
    client_cnf: /etc/my.cnf.d/client.cnf
    server_cnf: /etc/my.cnf.d/mariadb-server.cnf
  apt:
    socket: /var/run/mysqld/mysqld.sock
    client_cnf: /etc/mysql/mariadb.conf.d/50-client.cnf
    server_cnf: /etc/mysql/mariadb.conf.d/50-server.cnf
mariadb_server_socket:
  Debian: /var/run/mysqld/mysqld.sock
  RedHat: /var/lib/mysql/mysql.sock
mariadb_ansible_pkgs:
  Debian:
    - python3-pymysql
  RedHat:
    - python3-PyMySQL
