require_relative "../common"

Vagrant.configure("2") do |config|
  # config.vm.box = "generic/alma10" # not available
  config.vm.box = "almalinux/10" # 20GB
  # config.vm.box = "eurolinux-vagrant/almalinux-10" # not available
  # config.vm.box = "bento/almalinux-10" # with chef
  # config.vm.box = "openlogic/almalinux-9" # not available

  # if you want to extend disk size, you can use:
  # config.vm.disk :disk, size: "32GB", primary: true
  # config.vm.provision "extend_disk", type: "shell" do |shell|
  #   shell.inline = <<-SHELL
  #     if [ `df -k --output=size / | sed -n '$p'` -lt 20000000 ]; then
  #       echo "Disk size is less than 20GB, resizing..."
  #       sudo parted -s -f /dev/sda print
  #       echo Yes | sudo parted /dev/sda ---pretend-input-tty resizepart 4 100%
  #       sudo xfs_growfs /
  #       df -h /
  #     fi
  #   SHELL
  # end

  common_config(config)
end
