require_relative "../common"

Vagrant.configure("2") do |config|
  # config.vm.box = "generic/alma10" # not available
  config.vm.box = "almalinux/10" # 20GB
  # config.vm.box = "eurolinux-vagrant/almalinux-10" # not available
  # config.vm.box = "bento/almalinux-10" # with chef
  # config.vm.box = "openlogic/almalinux-10" # not available

  # if you want to extend disk size, you can use (defaut size 32GB):
  # expand_disk(config)

  common_config(config)
end
