setup_essential_roles:
  - env
  - pkg
  - update
  - time
  - lang
  - font
  - app
  - srv
setup_optional_roles:
  # tools
  - snap
  - anyenv
  - docker
  # applications
  - gui
  - git
  - ruby
  - vagrant
  # environments
  - vscode
