setup_essential_roles:
  - env
  - pkg
  - update
  - time
  - lang
  - font
  - app
setup_optional_roles:
  # tools
  - snap
  - docker
  - anyenv
  - mise
  # applications
  - gui
  - git
  - vagrant
  # services
  # - ds
  - mariadb
  - nginx
  - openldap
  - postgresql
  - redis
  - valkey
  # programing languages
  - nodejs
  - php
  - python
  - ruby
  - java
  # environments
  - vscode
