setup_essential_roles:
  - cert
  - env
  - pkg
  - update
  - time
  - lang
  - font
  - app
setup_optional_roles:
  # tools
  - anyenv
  - docker
  - git
  - mise
  - snap
  # services
  - nginx
  ## ldap
  - ds
  - openldap
  ## dasabase
  - mariadb
  - postgresql
  - redis
  - valkey
  # languages
  - java
  - nodejs
  - php
  - python
  - ruby
  # applications
  - gui
  - vagrant
  # environments
  - vscode
