- name: Task install on app for valkey
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ valkey_name }}'
      version: '{{ valkey_version }}'
      source: '{{ valkey_source }}'
      devel: '{{ valkey_devel }}'
      pkgs: '{{ valkey_libs | map("regex_replace", "^", "valkey-") }}'
