- name: Task install on app for python
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ python_name }}'
      version: '{{ python_version }}'
      source: '{{ python_source }}'
      devel: '{{ python_devel }}'
      pkgs: '{{ python_libs | map("regex_replace", "^", python_name ~ "-") }}'
