- name: Task install on app for python
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ python_name }}'
      ver: '{{ python_ver }}'
      src: '{{ python_src }}'
      dev: '{{ python_dev }}'

- name: Task install on app for python libs by pkg only
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      pkgs: '{{ python_libs | map("regex_replace", "^", python_name ~ "-") }}'
  when:
    - python_src == "pkg"
    - python_libs
