- name: Task install on git
  ansible.builtin.import_role:
    name: git
    tasks_from: install

- name: Git clone anyenv
  ansible.builtin.git:
    repo: https://github.com/anyenv/anyenv
    dest: ~/.anyenv
  environment: '{{ proxy_env }}'

- name: Block anyenv in bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK anyenv'
    block: |
      if ! [[ "$PATH" =~ "$HOME/.anyenv/bin:" ]]
      then
          export PATH="$HOME/.anyenv/bin:$PATH"
      fi
      eval "$(anyenv init -)"

- name: Make anyenv plugins directory
  ansible.builtin.file:
    path: ~/.anyenv/plugins
    state: directory
    mode: '0755'
  when: anyenv_update

- name: Git clone anyenv-update
  ansible.builtin.git:
    repo: https://github.com/znz/anyenv-update.git
    dest: ~/.anyenv/plugins/anyenv-update
  environment: '{{ proxy_env }}'
  when: anyenv_update
