- name: Task install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Task packages
  ansible.builtin.include_tasks:
    file: packages.yml
  loop: '{{ anyenv_envs }}'
  loop_control:
    loop_var: anyenv_env
