ds_name: '{{ ansible_facts.pkg_mgr == "dnf" | ternary("389-ds-base", "389-ds") }}'
ds_version: "" # "" is default, "latest" is latest stable, "x.y" is specific version
ds_source: pkg
ds_devel: false
ds_libs: []
ds_service_name: dirsrv@localhost.service
ds_service_auto: false
