ds_name: '{{ (ansible_facts.pkg_mgr == "dnf") | ternary("389-ds-base", "389-ds") }}'
ds_version: ""
ds_source: pkg
ds_devel: false
ds_libs: []
ds_service: false
ds_instance_name: localhost
ds_service_name: 'dirsrv@{{ ds_instance_name }}.service'
ds_config_create_suffix_entry: false
ds_config_sample_entries: false
ds_setup: true
