# config
#   modify data directory
# TODO: Ubuntuはまだ
---
- name: Create postgresql data directory
  become: true
  ansible.builtin.command:
    cmd: '{{ postgresql_server_setup }}'
    creates: '{{ postgresql_server_data }}/PG_VERSION'
  when: postgresql_server

- name: Set loopback md5 in pg_hba.conf
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: '{{ postgresql_server_data }}/pg_hba.conf'
    contype: host
    databases: all
    users: all
    address: '{{ item }}'
    method: md5
  loop:
    - "127.0.0.1/32"
    - "::1/128"
  notify: postgresql_restart_postgresql
  when:
    - postgresql_server
    - postgresql_config_allow_loopback_md5

- name: Set all md5 in pg_hba.conf
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: '{{ postgresql_server_data }}/pg_hba.conf'
    contype: host
    databases: all
    users: all
    address: all
    method: md5
  notify: postgresql_restart_postgresql
  when:
    - postgresql_server
    - postgresql_config_allow_all_md5
