- name: Set postgresql_install_pkgs
  ansible.builtin.set_fact:
    postgresql_install_pkgs: '{{ postgresql_libs | map("regex_replace", "^", postgresql_name ~ "-") }}'
  when: postgresql_source == "pkg"

- name: Add client package to postgresql_install_pkgs when apt
  ansible.builtin.set_fact:
    postgresql_install_pkgs: '{{ postgresql_install_pkgs | union([postgresql_name ~ "-client"]) }}'
  when:
    - postgresql_source == "pkg"
    - ansible_facts.pkg_mgr == "apt"

- name: Add server package to postgresql_install_pkgs when dnf
  ansible.builtin.set_fact:
    postgresql_install_pkgs: '{{ postgresql_install_pkgs | union([postgresql_name ~ "-server"]) }}'
  when:
    - postgresql_source == "pkg"
    - ansible_facts.pkg_mgr == "dnf"

- name: Task install on app for postgresql
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ postgresql_name }}'
      version: '{{ postgresql_version }}'
      source: '{{ postgresql_source }}'
      devel: '{{ postgresql_devel }}'
      pkgs: '{{ postgresql_install_pkgs | default([]) }}'

- name: Task list on os for postgresql_control_pkgs
  ansible.builtin.include_role:
    name: os
    tasks_from: list
  vars:
    os_list_os: '{{ postgresql_control_pkgs_os }}'

- name: Set postgresql_control_pkgs from os_list
  ansible.builtin.set_fact:
    postgresql_control_pkgs: '{{ os_list }}'

- name: Task install on app to control postgresql
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      pkgs: '{{ postgresql_control_pkgs }}'
