- name: Task install on app for nginx
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: nginx
      version: '{{ nginx_version }}'
      source: '{{ nginx_source }}'
      devel: '{{ nginx_devel }}'
      pkgs: '{{ nginx_libs | map("regex_replace", "^", "nginx-") }}'
