- name: Start and enable postgresql service
  become: true
  ansible.builtin.service:
    name: '{{ postgresql_service_name }}'
    state: started
    enabled: true
  when: postgresql_service

- name: Stop and disbale postgresql service
  become: true
  ansible.builtin.service:
    name: '{{ postgresql_service_name }}'
    state: stopped
    enabled: false
  when: not postgresql_service
