# - name: Copy nginx config file
#   become: true
#   ansible.builtin.template:
#     src: '{{ item }}.j2'
#     dest: '/etc/{{ item }}'
#     owner: root
#     group: root
#     mode: '0644'
#   loop:
#     - nginx/nginx.conf.j2
#   notify: nginx_restart
