- name: Start and enable nginx service
  become: true
  ansible.builtin.service:
    name: '{{ nginx_service_name }}'
    state: started
    enabled: true
  when: nginx_service_auto

- name: Stop and disbale nginx service
  become: true
  ansible.builtin.service:
    name: '{{ nginx_service_name }}'
    state: stopped
    enabled: false
  when: not nginx_service_auto
