# setup wsl

require "open3"
require "yaml"
require "win32/registry"

require_relative "setup"
require_relative "wsl"
setup_env_options = ENV.to_h
  .transform_keys(&:downcase)
  .select{|k, _| k.start_with?("setup_")})
  .transform_keys {|k| k.delete_prefix("setup_").to_sym}
setup_config_file = setup_env_options[:config_file] ||
  if FileTest.exist?("setup.yml")
    "setup.yml"
  else
    nil
  end
setup = Setup.new(setup_config_file, **setup_env_options)
wsl = WSL.new(distro: setup.name)

task default: :create

desc "Create WSL distribution"
task create: %i[distro ansible_playbook]

desc "Destroy WSL distribution"
task :destroy do
  if WSL.distro(setup.name)
    sh "wsl --unregister #{setup.name}"
    sleep 1 # wait for unregister
    rmdir setup.location if setup.location && FileTest.exist?(setup.location)
  end
end

task :wsl do
  case setup.version
  in 1
    unless WSL.status[:enable_wsl1]
      # install wsl with wsl1
      wsl --install --enable-wsl1 --no-distribution
      puts "Reboot after 10secs"
      sh "shutdown /r /t 10 /c \"Reboot for wsl installing.\""
      exit # no return
    end
  in 2
    unless WSL.status[:enable_wsl2]
      # install wsl
      sh "wsl --install --no-distribution"
      puts "Reboot after 10secs"
      sh "shutdown /r /t 10 /c \"Reboot for wsl installing.\""
      exit # no return
    end
  else
    raise "Unsupported WSL version: #{setup.version}"
  end
end

task distro: :wsl do
  case WSL.distro(setup.name)
  in {version: Integer}
    if version != setup.version
      sh "wsl --set-version #{setup.name} 1"
      WSL.clear
    end
  in nil
    # install distrobution
    install_option = String.new
    install_option << " --install #{setup.distro}" if setup.distro
    install_option << " --location #{setup.location}" if setup.location
    install_option << " --name #{setup.name}" if setup.name != setup.distro
    install_option << " --no-launch"
    install_option << " --version #{setup.version}"
    sh "wsl #{install_option}"
    WSL.clear

    if setup.input_user?
      puts "Run exit after setting username and password for WSL distribution."
      sh "wsl --distribution #{setup.name}"
    else
      open_lxss_registry(WSL.distro(setup.name)[:key], mode: "w") do |reg|
        reg["RunOOBE"] = 0
      end
    end
  end

  if setup.version.to_i == 1
    # NOTE: WSL1 では、/etc/resolv.conf のパーミッションが 0600 になってしまう。
    wsl.run("chmod 644 /etc/resolv.conf", user: "root")
  end
end

task pkg: :distro

desc "Update WSL distribution"
task update: :pkg do
  next if SETUP[:skip_update]

  run_opts = {user: "root"}
  pkg_mgr = wsl_pkg_mgr

  case pkg_mgr
  in "apt"
    apt_opts = +"-y"
    if proxy_required?
      ["http", "https", "ftp"].each do |proto|
        key = "#{proto}_proxy".intern
        value = SETUP[key]
        if value
          apt_opts << " -o Acquire::#{proto}::Proxy=\"#{value}\""
          apt_opts << " -o Acquire::#{proto}::Timeout=600"
        end
      end
    end
    wsl.run("apt update #{apt_opts}", **run_opts)
    wsl.run("apt upgrade #{apt_opts}", **run_opts)
    wsl.run("apt autoremove #{apt_opts}", **run_opts)
  in "dnf"
    dnf_opts = +"-y"
    if proxy_required?
      dnf_opts << " --setopt=proxy=#{proxy_uri}"
      dnf_opts << " --setopt=timeout=600"
    end
    wsl.run("dnf update #{dnf_opts}", **run_opts)
    wsl.run("dnf autoremove #{dnf_opts}", **run_opts)
  else
    raise "Unsupported package manager: #{pkg_mgr}"
  end
end

task ansible_playbook: %i[ansible ansible_playbook_wsl] do
  next if SETUP[:skip_ansible]

  # playbook with user
  pkg_mgr = wsl_pkg_mgr
  if pkg_mgr == "dnf"
    ["community.general", "community.mysql", "community.postgresql", "ansible.posix"].each do |collection|
      wsl.run("ansible-galaxy collection install #{collection}", env: proxy_env)
    end
  end

  option = String.new
  option << " -e @#{wsl_path(SETUP[:config])}" if FileTest.file?(SETUP[:config])
  option << " -e user_default=#{wsl_whoami}" if SETUP[:input_user]
  option << " -K" if SETUP[:require_password]
  env = {ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"}
  wsl.run("ansible-playbook all.yml #{option}", env:, cd: SETUP[:playbooks])
end

task ansible_playbook_wsl: :ansible do
  next if SETUP[:skip_ansible]

  # playbook with root
  puts "Setup wsl playbook"
  option = String.new
  option << " -e @#{wsl_path(SETUP[:config], user: 'root')}" if FileTest.file?(SETUP[:config])
  option << " -e wsl_default_user=#{wsl_whoami}"
  option << " -e user_name=#{SETUP[:username]}" if SETUP[:username]
  option << " -e user_password=#{SETUP[:password]}" if SETUP[:password]
  wsl.run("ansible-playbook wsl.yml #{option}", cd: SETUP[:playbooks], user: "root")
  sh "wsl --terminate #{setup.name}"
end

task ansible: %i[pkg update].compact do
  next if SETUP[:skip_ansible]

  pkg_mgr = wsl_pkg_mgr
  case pkg_mgr
  in "apt"
    wsl.run("apt install ansible -y", env: proxy_env, user: "root")
  in "dnf"
    wsl.run("dnf install ansible-core -y", env: proxy_env, user: "root")
    wsl.run("ansible-galaxy collection install community.general", env: proxy_env, user: "root")
  end
end
