# setup wsl

require "open3"
require "yaml"
require "win32/registry"

require_relative "setup"
require_relative "wsl"
setup_env_options = ENV.to_h
  .transform_keys(&:downcase)
  .select { |k, _| k.start_with?("setup_") }
  .transform_keys { |k| k.delete_prefix("setup_").to_sym }
setup_config_file = setup_env_options[:config_file] || ("setup.yml" if FileTest.exist?("setup.yml"))
setup = Setup.new(setup_config_file, **setup_env_options)
wsl = WSL.new(distro: setup.name)

task default: :create

desc "Create WSL distribution"
task create: %i[distro ansible_playbook]

desc "Destroy WSL distribution"
task :destroy do
  if wsl.installed?
    sh "wsl --unregister #{setup.name}"
    puts "sleep 1sec for unregistering WSL distribution..."
    sleep 1 # wait for unregister
    rmdir setup.location if setup.location && FileTest.exist?(setup.location)
  end
end

task :wsl do
  case setup.version
  in 1
    unless WSL.status[:enable_wsl1]
      # install wsl with wsl1
      sh "wsl --install --enable-wsl1 --no-distribution"
      puts "Reboot after 10secs"
      sh "shutdown /r /t 10 /c \"Reboot for wsl installing.\""
      exit # no return
    end
  in 2
    unless WSL.status[:enable_wsl2]
      # install wsl
      sh "wsl --install --no-distribution"
      puts "Reboot after 10secs"
      sh "shutdown /r /t 10 /c \"Reboot for wsl installing.\""
      exit # no return
    end
  else
    raise "Unsupported WSL version: #{setup.version}"
  end
end

task distro: :wsl do
  unless wsl.installed?
    # install distrobution
    install_option = String.new
    install_option << " --install #{setup.distro}"
    install_option << " --location #{setup.location}" if setup.location
    install_option << " --name #{setup.name}" if setup.name != setup.distro
    install_option << " --version #{setup.version}" if setup.version == 1
    install_option << " --no-launch"
    sh "wsl #{install_option}"
    WSL.clear
  end

  if wsl.version != setup.version
    sh "wsl --set-version #{setup.name} #{setup.version}"
    WSL.clear
  end

  if wsl.oobe
    if setup.input_user?
      puts "Run exit after setting username and password for WSL distribution."
      sh "wsl --distribution #{setup.name}"
    else
      wsl.oobe = false
    end
  end

  if wsl.uid.zero?
    if setup.input_user?
      warn "Maybe bug: Already run oobe, but uid is still 0. Force to run oobe again."
      puts "Run exit after setting username and password for WSL distribution."
      sh "wsl --distribution #{setup.name}"
    else
      current_users= wsl.users
      current_groups = wsl.groups

      unless current_groups.include?(setup.groupname)
        groupadd_opts = String.new
        groupadd_opts << " -g #{setup.gid}"
        wsl.run("groupadd #{groupadd_opts} \"#{setup.groupname}\"", user: "root")
      end

      unless current_users.include?(setup.username)
        useradd_opts = String.new
        useradd_opts << " -u #{setup.uid}"
        useradd_opts << " -g #{setup.gid}"
        available_groups = setup.groups & current_groups
        useradd_opts << " -G \"#{available_groups.join(',')}\"" unless available_groups.empty?
        useradd_opts << " -m"
        wsl.run("useradd #{useradd_opts} \"#{setup.username}\"", user: "root")
        begin
          wsl.run("chpasswd", capture: true, stdin_data: "#{setup.username}:#{setup.password}", user: "root")
        rescue
          wsl.run("userdel -r \"#{setup.username}\"", user: "root")
          raise
        end
      end

      wsl.uid = 1000
      sh "wsl --terminate #{setup.name}"
    end
  end

  if setup.version.to_i == 1
    # FIXME: WSL1では、パーミションが0700の/etc/resolv.confが作成されてしまう場合がある。
    #    本来は自動生成されるファイルへのシンボリックリンクなるべき。
    if wsl.run("realpath /etc/resolv.conf", capture: true, exception: false)&.chomp == "/etc/resolv.conf"
      wsl.run("rm -f /etc/resolv.conf", user: "root")
      sh "wsl --terminate #{setup.name}"
    end
  end
end

task pkg: :distro

desc "Update WSL distribution"
task update: :pkg do
  next if setup.skip_update?

  run_opts = {user: "root"}

  case wsl.pkg_mgr
  in "apt"
    wsl.run("apt update -y #{setup.apt_opts}", **run_opts)
    wsl.run("apt upgrade -y #{setup.apt_opts}", **run_opts)
    wsl.run("apt autoremove -y #{setup.apt_opts}", **run_opts)
  in "dnf"
    wsl.run("dnf update -y #{setup.dnf_opts}", **run_opts)
    wsl.run("dnf autoremove -y #{setup.dnf_opts}", **run_opts)
  else
    raise "Unsupported package manager: #{wsl.pkg_mgr}"
  end
end

task ansible: %i[pkg update].compact do
  next if setup.skip_ansible?

  case wsl.pkg_mgr
  in "apt"
    wsl.run("apt install ansible -y #{setup.apt_opts}", user: "root")
  in "dnf"
    wsl.run("dnf install ansible-core -y #{setup.dnf_opts}", user: "root")
    # for root
    ["community.general"].each do |collection|
      wsl.run("ansible-galaxy collection install #{collection}", env: setup.proxy_env, user: "root")
    end
    # for user
    ["community.general", "community.mysql", "community.postgresql", "ansible.posix"].each do |collection|
      wsl.run("ansible-galaxy collection install #{collection}", env: setup.proxy_env)
    end
  end
end

task ansible_playbook: %i[ansible ansible_playbook_wsl] do
  next if setup.skip_ansible?

  # opt = String.new
  # opt << " -e @#{wsl.path(setup.config_file)}" if setup.config_file
  # if setup.input_user?
  #   opt << " -K"
  # else
  #   opt << " -e ansible_become_password=\"#{setup.passwd}\""
  # end
  # opt << " -K" if SETUP[:require_password]
  # env = {ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"}

  # wsl.run("ansible-playbook setup.yml #{opt}", env:, cd: setup.playbooks)
end

task ansible_playbook_wsl: :ansible do
  next if setup.skip_ansible?

  # playbook with root
  opt = String.new
  opt << " -e @#{wsl.path(setup.config_file)}" if setup.config_file
  wsl.run("ansible-playbook wsl.yml #{opt}", cd: setup.playbooks, user: "root")
  sh "wsl --terminate #{setup.name}"
end
