- name: Task facts
  ansible.builtin.import_tasks:
    file: facts.yml

- name: Task wsl_conf
  ansible.builtin.import_tasks:
    file: wsl_conf.yml

- name: Task mount_drive
  ansible.builtin.include_tasks:
    file: mount_drive.yml
  loop: '{{ wsl_mount_drives }}'
  loop_control:
    loop_var: wsl_mount_drive
  when: wsl_mount_drives is defined
