cert_update_cmd_os:
  Debian: update-ca-certificates
  RedHat: update-ca-trust
cert_ca_dir_os:
  Debian: /usr/local/share/ca-certificates
  RedHat: /etc/pki/ca-trust/source/anchors
cert_ca_file_os:
  Debian: /etc/ssl/certs/ca-certificates.crt
  RedHat: /etc/pki/tls/certs/ca-bundle.crt
