require_relative "../common"

Vagrant.configure("2") do |config|
  # config.vm.box = "generic/ubuntu2404" # not avialable and broken nameservers
  # config.vm.box = "ubuntu/noble64" # not avialable
  config.vm.box = "bento/ubuntu-24.04" # with chef

  # if you want to extend disk size, you can use (defaut size 32GB):
  # expand_disk(config)

  common_config(config)
end
