- name: Install packages by apt
  become: true
  ansible.builtin.apt:
    name: '{{ app_install_pkg }}'
    install_recommends: '{{ app_install_recommends }}'

- name: Install build packages by apt
  become: true
  ansible.builtin.apt:
    name: build-essential
    install_recommends: false
  when: app_install_dev

- name: Install dev packages by apt
  become: true
  ansible.builtin.apt:
    name: >-
      {{ (app_install_pkg is string) | ternary(
        app_install_pkg ~ "-dev",
        app_install_pkg | map("regex_replace", "$", "-dev")
      ) }}
    install_recommends: '{{ app_install_recommends }}'
  when: app_install_dev
