- name: Install packages by dnf
  become: true
  ansible.builtin.dnf:
    name: '{{ app_install_pkg }}'
    install_weak_deps: '{{ app_install_recommends }}'
  when: app_install_pkg | length > 0

- name: Install dev packages by apt
  become: true
  ansible.builtin.dnf:
    name: '{{ app_install_pkg | map("regex_replace", "$", "-devel") }}'
    install_weak_deps: '{{ app_install_recommends }}'
  when:
    - app_install_pkg | length > 0
    - app_install_dev
