# install packages
---
- name: Debug app_install
  ansible.builtin.debug:
    var: app_install
  when: debug | default(false)

- name: Set app_install_* facts from app_install
  ansible.builtin.set_fact:
    app_install_name: '{{ app_install.name | default("") }}'
    app_install_version: '{{ app_install.version | default("") }}'
    app_install_pkgs: '{{ app_install.pkgs | default([]) }}'
    app_install_source: '{{ app_install.source | default("pkg") }}'
    app_install_recommends: '{{ app_install.recommends | default(true) }}'
    app_install_devel: '{{ app_install.devel | default(false) }}'

- name: 'Task package manager {{ ansible_facts.pkg_mgr }}'
  ansible.builtin.include_tasks:
    file: 'install_{{ ansible_facts.pkg_mgr }}.yml'
  when: app_install_source == "pkg"

# TODO: 他のソース
#   snap, rbenv, pyenv, nodenv, *env

- name: 'Task other source {{ app_install_source }}'
  ansible.builtin.include_tasks:
    file: 'install_{{ app_install_source }}.yml'
  when: app_install_source != "pkg"
