- name: Install package by apt
  become: true
  ansible.builtin.apt:
    name: '{{ app_install_name }}'
    install_recommends: '{{ app_install_recommends }}'
  when: app_install_name

- name: Install packages by apt
  become: true
  ansible.builtin.apt:
    name: '{{ app_install_pkgs }}'
    install_recommends: '{{ app_install_recommends }}'
  when: app_install_pkgs | length > 0

- name: Install build packages by apt
  become: true
  ansible.builtin.apt:
    name: build-essential
    install_recommends: false
  when: app_install_dev

- name: Install dev package by apt
  become: true
  ansible.builtin.apt:
    name: '{{ app_install_name }}-dev'
    install_recommends: '{{ app_install_recommends }}'
  when: app_install_name and app_install_dev

