- name: 'Task package manager {{ ansible_pkg_mgr }}'
  ansible.builtin.include_tasks:
    file: 'install_{{ ansible_pkg_mgr }}.yml'
  when: app_src == "pkg"

- name: 'Task package manager {{ ansible_pkg_mgr }}'
  ansible.builtin.include_tasks:
    file: 'install_{{ app_src }}.yml'
  when: app_src != "pkg"
