# rbenv
- name: Assert app_install_version is not empty when rbenv is used
  ansible.builtin.assert:
    that: app_install_version != ""
    fail_msg: "app_install_version is required when rbenv is used"
    quiet: true

- name: Task facts on anyenv
  ansible.builtin.import_role:
    name: anyenv
    tasks_from: facts

- name: Install ruby by rbenv
  ansible.builtin.shell:
    cmd: |
      {{ anyenv_shell_block }}
      rbenv install -s {{ app_install_version }}
    executable: /bin/bash
  register: anyenv_install_rbenv_result_install
  changed_when: anyenv_install_rbenv_result_install.stdout != ""

- name: Get global ruby version of rbenv
  ansible.builtin.shell:
    cmd: |
      {{ anyenv_shell_block }}
      rbenv global
    executable: /bin/bash
  register: anyenv_install_rbenv_result_global
  changed_when: false

- name: Set global version of rbenv
  ansible.builtin.shell:
    cmd: |
      {{ anyenv_shell_block }}
      {{ rbenv_path }} global {{ ruby.version }}
    executable: /bin/bash
  changed_when: true
  when: anyenv_install_rbenv_result_global.stdout | trim != app_install_version
