- name: Task install
  ansible.builtin.include_tasks:
    file: install.yml
  vars:
    app_install:
      pkgs: '{{ app_pkgs }}'
      recommends: '{{ app_recommends }}'
  when: app_pkgs | length > 0

- name: Task alternatives
  ansible.builtin.import_tasks:
    file: alternatives.yml
