- name: Task install
  ansible.builtin.include_tasks:
    file: install.yml
  vars:
    app_install_pkgs: '{{ app_pkgs }}'
    app_install_recommends: '{{ app_recommends }}'
  when: app_pkgs | length > 0

- name: Task alternatives
  ansible.builtin.import_tasks:
    file: alternatives.yml
