- name: Restart postgresql service
  become: true
  ansible.builtin.service:
    name: '{{ postgresql_service_name }}'
    state: restarted
  when: postgresql_service
  listen: postgresql_restart_postgresql
