- name: Stat localhost dirsrv
  become: true
  ansible.builtin.stat:
    path: '/etc/dirsrv/slapd-{{ ds_instance_name }}'
  register: ds_config_dirsrv_stat

- name: Crate temp directory
  ansible.builtin.tempfile:
    state: directory
  register: ds_config_tempdir
  when: not ds_config_dirsrv_stat.stat.exists

- name: Create 389 DS setup file
  ansible.builtin.template:
    src: '389ds.inf.j2'
    dest: '{{ ds_config_tempdir.path }}/389ds.inf'
    mode: '0644'
  when: not ds_config_dirsrv_stat.stat.exists

- name: Run dscreate
  become: true
  ansible.builtin.command:
    argv:
      - dscreate
      - from-file
      - '{{ ds_config_tempdir.path }}/389ds.inf'
  changed_when: true
  when: not ds_config_dirsrv_stat.stat.exists
