- name: Task install on app for ds
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ ds_name }}'
      version: '{{ ds_version }}'
      source: '{{ ds_source }}'
      devel: '{{ ds_devel }}'
      pkgs: '{{ ds_libs | map("regex_replace", "^", ds_name ~ "-") }}'
