- name: Task install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Task config
  ansible.builtin.import_tasks:
    file: config.yml

- name: Task serivce
  ansible.builtin.import_tasks:
    file: service.yml

- name: Role ldap
  ansible.builtin.import_role:
    name: ldap
  vars:
    ldap_server_uri: 'ldap://localhost'
    ldap_bind_dn: '{{ ds_config_root_dn }}'
    ldap_bind_pw: '{{ ds_config_root_password }}'
    ldap_base: '{{ ds_config_suffix }}'
