- name: Start and enable 389-ds service
  become: true
  ansible.builtin.service:
    name: '{{ ds_service_name }}'
    state: started
    enabled: true
  when: ds_service

- name: Stop and disbale 389-ds service
  become: true
  ansible.builtin.service:
    name: '{{ ds_service_name }}'
    state: stopped
    enabled: false
  when: not ds_service
