require 'digest/md5'

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2004'
  config.vm.box_check_update = true

  hostname = File.basename(File.absolute_path(__dir__)).gsub('_', '-')
  ssh_port = 10_000 + (Digest::MD5.digest(hostname).unpack1('L') % 20_000)

  config.vm.hostname = hostname

  config.vm.network 'forwarded_port', guest: 22, host: ssh_port, host_ip: '127.0.0.1', id: 'ssh'

  config.vm.synced_folder '.', '/vagrant', disabled: true
  # config.vm.synced_folder '.', '/vagrant', type: 'rsync'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.provider 'hyperv' do |hv|
    hv.cpus = 2
    hv.maxmemory = 4096
  end

  # do manual 'vagrant vbguest --do install'
  config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')

  config.timezone.value = 'Asia/Tokyo' if Vagrant.has_plugin?('vagrant-timezone')

  proxy_protocols = %w[http https ftp].to_h do |name|
    env_name = "#{name}_proxy"
    env_value = ENV[env_name]
    if env_value
      [name, {name: env_name, value: env_value}]
    else
      [name, nil]
    end
  end.compact

  proxy_enable = !proxy_protocols.empty?

  if proxy_enable && Vagrant.has_plugin?('vagrant-proxyconf')
    proxy_protocols.each do |name, env|
      config.proxy.__send__("#{name}=", env[:value])
    end

    config.proxy.no_proxy = ENV['no_proxy'] if ENV.has_key?('no_proxy')

    # cannot write snap npm, so disable
    config.proxy.enabled = {npm: false}
  end

  config.vm.provision 'fix-dns', type: 'shell', before: :all do |script|
    script.inline = <<-SHELL
      sudo sed -i -e '/nameservers:/d' -e '/addresses:/d' /etc/netplan/01-netcfg.yaml
      sudo netplan generate && sudo netplan apply
      sudo sed -i 's/^[[:alpha:]]/#&/' /etc/systemd/resolved.conf
      sudo systemctl restart systemd-resolved.service
    SHELL
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = '../../ansible/ubuntu2004/setup.yml'
    vars = {
      ruby_version: '2.7',
      node_version: '14',
    }

    proxy_protocols.each_value { |env| vars[env[:name]] = env[:value] } if proxy_enable

    %w[name email].each do |name|
      value = `git config --get user.#{name}`.chomp
      vars["git_config_user_#{name}"] = value if value&.length&.positive?
    end

    ansible.extra_vars = vars
  end
end
