- name: Start and enable openldap service
  become: true
  ansible.builtin.service:
    name: '{{ openldap_service_name }}'
    state: started
    enabled: true
  when: openldap_service

- name: Stop and disbale openldap service
  become: true
  ansible.builtin.service:
    name: '{{ openldap_service_name }}'
    state: stopped
    enabled: false
  when: not openldap_service
