- name: Clone git repository yuzakan
  ansible.builtin.git:
    repo: https://github.com/kue-ipc/yuzakan.git
    dest: ~/yuzakan
    version: main

- name: Run bundle install
  ansible.builtin.shell:
    cmd: bundle install
    executable: /bin/bash
    chdir: ~/yuzakan
  changed_when: true

- name: Run npm install
  ansible.builtin.shell:
    cmd: npm install
    executable: /bin/bash
    chdir: ~/yuzakan
  changed_when: true

- name: Run bundle exec rake build
  ansible.builtin.shell:
    cmd: bundle exec rake build
    executable: /bin/bash
    chdir: ~/yuzakan
  changed_when: true

- name: Run bundle exec hanami db prepare
  ansible.builtin.shell:
    cmd: bundle exec hanami db prepare
    executable: /bin/bash
    chdir: ~/yuzakan
  changed_when: true


- name: Run bundle exec hanami db prepare for test
  ansible.builtin.shell:
    cmd: bundle exec hanami db prepare
    executable: /bin/bash
    chdir: ~/yuzakan
  changed_when: true
  environment:
    HANAMI_ENV: test
