require_relative '../common'

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/rocky8'

  config.vm.box_check_update = true

  hostname = File.basename(File.absolute_path(__dir__)).gsub('_', '-')
  ssh_port = calc_port(hostname)

  config.vm.hostname = hostname

  config.vm.network 'forwarded_port', guest: 22, host: ssh_port, host_ip: '127.0.0.1', id: 'ssh'

  config.vm.synced_folder '.', '/vagrant', disabled: true
  # config.vm.synced_folder '.', '/vagrant', type: 'rsync'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.provider 'hyperv' do |hv|
    hv.cpus = 2
    hv.maxmemory = 4096
  end

  # enable env
  config.env.enable if Vagrant.has_plugin?('vagrant-env')

  # do manual 'vagrant vbguest --do install'
  config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')

  # BUG... selinux enforced
  # config.timezone.value = 'Asia/Tokyo' if Vagrant.has_plugin?('vagrant-timezone')

  proxy = get_proxy

  if Vagrant.has_plugin?('vagrant-proxyconf')
    if proxy
      config.proxy.enabled = true
      %i[http https ftp].each do |name|
        config.proxy.__send__("#{name}=", proxy[name]) if proxy[name]
      end
      config.proxy.no_proxy = proxy[:no_proxy] if proxy[:no_proxy]
    else
      config.proxy.enabled = false
    end
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = '../../ansible/setup.yml'
    setup = {
      pkgs: [
        'vim',
        'rsync',
        '@Development Tools',
      ],
    }
    # EL8 can specify app version
    app = {
      # ds: {
      #   user_group: 'account', # or 'preson'
      #   member_of: true,
      # },
      git: {
        config: git_config,
      },
      mariadb: {
        vresion: '10.3',
        dev: true,
      },
      nginx: {
        version: '1.20',
      },
      nodejs: {
        version: '18',
        npms: [
          'coffeescript',
          'npm-check-updates',
        ],
      },
      # openldap: {
      #   user_group: 'account', # or 'preson'
      #   member_of: true,
      # },
      reids: {
        version: '6',
        dev: true,
      },
      ruby: {
        version: '2.5',
        dev: true,
        pkgs: [
          'ruby-irb',
          'rubygem-rake',
          'rubygem-bundler',
          'rubygem-mysql2',
        ],
        gems: [
          'rubocop',
          'nokogiri',
        ],
      },
    }

    ansible.extra_vars = {
      setup: setup,
      app: app,
      proxy: proxy,
    }.compact
  end
end
