- name: Task install on app for redis
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ redis_name }}'
      version: '{{ redis_version }}'
      source: '{{ redis_source }}'
      devel: '{{ redis_devel }}'
      pkgs: '{{ redis_libs | map("regex_replace", "^", "redis-") }}'
