- name: Start and enable redis service
  become: true
  ansible.builtin.service:
    name: '{{ redis_service_name }}'
    state: started
    enabled: true
  when: redis_service

- name: Stop and disbale redis service
  become: true
  ansible.builtin.service:
    name: '{{ redis_service_name }}'
    state: stopped
    enabled: false
  when: not redis_service
