require_relative "../common"

Vagrant.configure("2") do |config|
  config.vm.box = "openindiana/hipster"

  config.vm.box_check_update = true

  hostname = File.basename(File.absolute_path(__dir__)).gsub("_", "-")
  ssh_port = calc_port(hostname)

  config.vm.hostname = hostname

  config.vm.network "forwarded_port", guest: 22, host: ssh_port, host_ip: "127.0.0.1", id: "ssh"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.provider "hyperv" do |hv|
    hv.cpus = 2
    hv.maxmemory = 4096
  end
end
