- name: Run dpkg --print-architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  changed_when: false
  register: apt_run_dpkg_print_architecture

- name: Set apt_architecture
  ansible.builtin.set_fact:
    apt_architecture: '{{ apt_run_dpkg_print_architecture.stdout_lines | first | trim }}'

- name: Set apt_release
  ansible.builtin.set_fact:
    apt_release: '{{ ansible_facts.distribution_release }}'
