- name: Assert ansible_pkg_mgr is apt
  ansible.builtin.assert:
    that: ansible_pkg_mgr == "apt"
    msg: "ansible_pkg_mgr is not apt, but {{ ansible_pkg_mgr }}"
    quiet: true

- name: Task facts
  ansible.builtin.import_tasks:
    file: facts.yml

- name: Task etc on proxy
  ansible.builtin.include_role:
    name: snap
    tasks_from: proxy
  vars:
    proxy_etc_role_path: '{{ role_path }}'
    proxy_etc_files: '{{ apt_proxy_etc_files }}'
  when: proxy_env != {}
