# add repository
---
- name: Assert ansible_facts.pkg_mgr is apt
  ansible.builtin.assert:
    that: ansible_facts.pkg_mgr == "apt"
    msg: "ansible_facts.pkg_mgr is not apt, but {{ ansible_facts.pkg_mgr }}"
    quiet: true

- name: Debug apt_repo
  ansible.builtin.debug:
    var: apt_repo
  when: debug

- name: Add deb822 repository
  become: true
  ansible.builtin.deb822_repository:
    name: '{{ apt_repo.name }}'
    types: '{{ app_repo.type | default("deb") }}'
    uris: '{{ apt_repo.url }}'
    suites: '{{ apt_repo.suite | default(ansible_facts.distribution_release) }}'
    components: '{{ apt_repo.component }}'
    signed_by: '{{ app_repo.gpg }}'
  when: apt_repo is not string

- name: Add apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: '{{ apt_repo }}'
  when: apt_repo is string
