require_relative '../common'

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/rocky9'

  config.vm.box_check_update = true

  hostname = File.basename(File.absolute_path(__dir__)).gsub('_', '-')
  ssh_port = calc_port(hostname)

  config.vm.hostname = hostname

  config.vm.network 'forwarded_port', guest: 22, host: ssh_port, host_ip: '127.0.0.1', id: 'ssh'

  config.vm.synced_folder '.', '/vagrant', disabled: true
  # config.vm.synced_folder '.', '/vagrant', type: 'rsync'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.provider 'hyperv' do |hv|
    hv.cpus = 2
    hv.maxmemory = 4096
  end

  # enable env
  config.env.enable if Vagrant.has_plugin?('vagrant-env')

  # do manual 'vagrant vbguest --do install'
  config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')

  proxy = get_proxy

  if Vagrant.has_plugin?('vagrant-proxyconf')
    if proxy
      config.proxy.enabled = true
      %i[http https ftp].each do |name|
        config.proxy.__send__("#{name}=", proxy[name]) if proxy[name]
      end
      config.proxy.no_proxy = proxy[:no_proxy] if proxy[:no_proxy]
    else
      config.proxy.enabled = false
    end
  end

  config.vm.provision 'ansible' do |ansible|
    ENV['ANSIBLE_INJECT_FACT_VARS'] = 'False'
    ansible.compatibility_mode = '2.0'
    ansible.playbook = '../../ansible/el9/setup.yml'
    vars = {
      setup: {
        pkgs: [
          'vim',
          'rsync',
          '@Development Tools',
        ],
      },
    }

    vars[:proxy] = proxy if proxy

    vars[:git][:config] = git_config if vars[:git]

    ansible.extra_vars = vars
  end

  config.vm.provision 'nginx', type: 'ansible' do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = 'nginx.yml'
    vars = {
      tls_file: {
        cert: '/etc/pki/tls/certs/server.crt',
        key: '/etc/pki/tls/private/server.key',
      },
      firewall_mgr: 'firewalld',
      geoip: {
        account_id: ENV['GEOIP_ACCOUNT_ID'],
        license_key: ENV['GEOIP_LICENSE_KEY'],
      },
    }
    vars[:proxy] = proxy if proxy
    ansible.extra_vars = vars
  end
end
