# Copy etc files for proxy setting
---
- name: Make diretory
  become: true
  ansible.builtin.file:
    path: '/etc/{{ item }}'
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop: '{{ proxy_etc_files | map("dirname") }}'

- name: Copy template config to etc directory for proxy
  become: true
  ansible.builtin.template:
    src: '{{ proxy_etc_role_path | default(role_path) }}/templates/{{ item }}.j2'
    dest: '/etc/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  notify: '{{ proxy_etc_notify | default([]) }}'
  loop: '{{ proxy_etc_files }}'

- name: Reset variables
  ansible.builtin.set_fact:
    proxy_etc_role_path: '{{ role_path }}'
    proxy_etc_files: []
    proxy_etc_notify: []
