- name: Setting proxy_env var from proxy_*
  ansible.builtin.set_fact:
    proxy_env:
      http_proxy: '{{ proxy_http | default(omit) }}'
      https_proxy: '{{ proxy_https | default(omit) }}'
      ftp_proxy: '{{ proxy_ftp | default(omit) }}'
      no_proxy: >-
        {{ proxy_no | default(
          (proxy_bypass_loopback | ternary(proxy_loopback, []) + proxy_bypass_list) | unique | join(",")) }}
  when:
    - proxy_env is not defined
    - proxy_http is defined or proxy_https is defined or proxy_ftp is defined

- name: Setting proxy_env var from env
  ansible.builtin.set_fact:
    proxy_env:
      http_proxy: '{{ lookup("env", "http_proxy", default=omit) }}'
      https_proxy: '{{ lookup("env", "https_proxy", default=omit) }}'
      ftp_proxy: '{{ lookup("env", "ftp_proxy", default=omit) }}'
      no_proxy: '{{ lookup("env", "no_proxy", default=omit) }}'
  when:
    - proxy_env is not defined
    - lookup("env", "http_proxy") != "" or lookup("env", "https_proxy") != "" or lookup("env", "http_proxy") != ""

- name: Setting proxy_env var to empty
  ansible.builtin.set_fact:
    proxy_env: {}
  when: proxy_env is not defined

- name: Debug proxy_env
  ansible.builtin.debug:
    var: proxy_env
  when: debug | default(false)
