anyenv_shell_block: |
  if ! [[ "$PATH" =~ "$HOME/.anyenv/bin:" ]]
  then
      export PATH="$HOME/.anyenv/bin:$PATH"
  fi
  eval "$(anyenv init -)"

anyenv_pkgs:
  # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
  pyenv:
    Debian:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - git
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    RedHat:
      - gcc
      - make
      - patch
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
  # https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
  rbenv:
    Debian:
      - build-essential
      - autoconf
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev
      - libffi-dev
      - libgmp-dev
      - rustc
    RedHat:
      - autoconf
      - gcc
      - patch
      - bzip2
      - openssl-devel
      - libffi-devel
      - readline-devel
      - zlib-devel
      - gdbm-devel
      - ncurses-devel
      - tar
      - perl-FindBin
      - libyaml-devel
      - rust
