# https://mise.jdx.dev/getting-started.html#installing-mise-cli
- name: Task repo on apt for mise
  ansible.builtin.include_role:
    name: apt
    tasks_from: repo
  vars:
    apt_repo:
      name: mise
      url: https://mise.jdx.dev/deb
      suites: stable
      component: main
      gpg: https://mise.jdx.dev/gpg-key.pub

- name: 'Task repo_{{ ansible_facts.pkg_mgr }}'
  ansible.builtin.include_tasks:
    file: repo_{{ ansible_facts.pkg_mgr }}.yml
# https://mise.jdx.dev/getting-started.html#installing-mise-cli

- name: Assert ansible_facts.pkg_mgr is dnf
  ansible.builtin.assert:
    that: ansible_facts.pkg_mgr == "dnf"
    msg: "ansible_facts.pkg_mgr is not dnf, but {{ ansible_facts.pkg_mgr }}"
    quiet: true

- name: Add mise repo
  become: true
  community.general.copr:
    name: '@jdxcode/mise'
  environment: '{{ proxy_env }}'


- name: Task install on app for git
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: mise
