# use mise.run
- name: Run mise.run
  become: true
  ansible.builtin.shell:
    cmd: '{{ lookup("ansible.builtin.url", "https://mise.run") }}'
    executable: /bin/sh
    creates: ~/.local/bin/mise
  environment: '{{ proxy_env }}'
