# use mise.run

- name: Run mise.run
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl https://mise.run | sh
    executable: /bin/bash
    creates: ~/.local/bin/mise
  environment: '{{ proxy_env }}'
