# https://mise.jdx.dev/getting-started.html#installing-mise-cli
- name: Task repo on apt for mise
  ansible.builtin.import_role:
    name: apt
    tasks_from: repo
  vars:
    apt_repo:
      name: mise
      url: https://mise.jdx.dev/deb
      suites: stable
      component: main
      gpg: https://mise.jdx.dev/gpg-key.pub
