# base DN

- name: Add ldap entry base dn
  community.general.ldap_entry:
    dn: '{{ ldap_base }}'
    objectClass:
      - top
      - dcObject
      - organization
    attributes:
      dc: '{{ ldap_base | split(",") | first | split("=") | last }}'
      o: '{{ ldap_organization }}'
  args: '{{ ldap_connect }}'
