- name: Task list on os for ldap_control_pkgs
  ansible.builtin.include_role:
    name: os
    tasks_from: list
  vars:
    os_list_os: '{{ ldap_control_pkgs_os }}'

- name: Set ldap_control_pkgs from os_list
  ansible.builtin.set_fact:
    ldap_control_pkgs: '{{ os_list }}'

- name: Task install on app to control ldap
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      pkgs: '{{ ldap_control_pkgs }}'
