- name: Task base
  ansible.builtin.include_tasks:
    file: base.yml

- name: Task posix person
  ansible.builtin.include_tasks:
    file: 'posix_{{ ldap_posix }}.yml'

- name: Task member
  ansible.builtin.include_tasks:
    file: member.yml
  when: ldap_member
