nodejs_name: '{{ nodejs_name_src[nodejs_source] }}'
nodejs_version: ""
nodejs_source: pkg
nodejs_devel: false
nodejs_libs: []
nodejs_dep_pkgs: '{{ nodejs_dep_pkgs_src[nodejs_source] | default([]) }}'
nodejs_pkg_mgr: "npm" # yarn, pnpm, bun
nodejs_npms: []
nodejs_env: {}
