mariadb_name: mariadb
mariadb_version: ""
mariadb_source: pkg
mariadb_devel: false
mariadb_libs: []
mariadb_server: false
# config
mariadb_config_charset: utf8mb4
mariadb_config_collation: utf8mb4_general_ci
# service
mariadb_service: false
mariadb_service_name: mariadb.service
mariadb_service_auto: false
