- name: Setup
  hosts: localhost
  tasks:
    - debug:
        msg: "setup.yml is not intended to be run directly. Please use the Rakefile to run the playbook."
      become: true
  # vars:
  #   user_name: '{{ user_name | default(wsl_default_user | default(ansible_user)) }}'
  # roles:
  #   - user
  #   # - wsl
