ruby_name_src:
  pkg: ruby
  snap: ruby
  mise: ruby
  anyenv: rbenv
ruby_dep_pkgs_src:
  pkg: []
  snap: []
  mise: []
  anyenv: '{{ ruby_dep_pkgs_build }}'
ruby_dep_pkgs_build: '{{ ruby_dep_pkgs_build_os_family[ansible_facts.os_family] | default([]) }}'
# https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
ruby_dep_pkgs_build_os_family:
  Debian:
    - build-essential
    - autoconf
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
    - libffi-dev
    - libgmp-dev
    - rustc
  RedHat:
    - autoconf
    - gcc
    - patch
    - bzip2
    - openssl-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
    - tar
    - perl-FindBin
    - libyaml-devel
    - rust
