- name: Clone git repository ikamail
  ansible.builtin.git:
    repo: https://github.com/kue-ipc/ikamail.git
    dest: ~/ikamail
    version: main

- name: Run bundle install
  ansible.builtin.shell:
    cmd: bundle install
    executable: /bin/bash
    chdir: ~/ikamail
  changed_when: true

- name: Run rails yarn:install
  ansible.builtin.shell:
    cmd: bin/rails yarn:install
    executable: /bin/bash
    chdir: ~/ikamail
  changed_when: true

- name: Check rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails db:version
    executable: /bin/bash
    chdir: ~/ikamail
  ignore_errors: yes
  register: ikamail_rails_db_version_result

- name: Run rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails db:setup
    executable: /bin/bash
    chdir: ~/ikamail
  changed_when: true
  when: ikamail_rails_db_version_result is failed

- name: Run rails db:migrate
  ansible.builtin.shell:
    cmd: bin/rails db:migrate
    executable: /bin/bash
    chdir: ~/ikamail
  changed_when: true
  when: ikamail_rails_db_version_result is not failed

