# 
- name: Install devel packages for ikamail
  become: yes
  ansible.builtin.dnf:
    name:
      - libyaml-devel
      - libffi-devel

- name: Clone git repository ikamail
  ansible.builtin.git:
    repo: https://github.com/kue-ipc/ikamail.git
    dest: ~/ikamail
    version: main

- name: Run bundle install
  ansible.builtin.shell:
    cmd: bundle install
    executable: /bin/bash
    chdir: ~/ikamail

- name: Run rails yarn:install
  ansible.builtin.shell:
    cmd: bin/rails yarn:install
    executable: /bin/bash
    chdir: ~/ikamail

# - name: check rails db version
#   ansible.builtin.shell:
#     cmd: bin/rails yarn:install
#     executable: /bin/bash
#     chdir: ~/ikamail

#   command:
#     argv:
#       - bash
#       - '-lic'
#       - bin/rails db:version
#     chdir: ~/ikamail
#   ignore_errors: yes
#   register: rails_db_version_result

- name: Run rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails db:setup
    executable: /bin/bash
    chdir: ~/ikamail
  # command:
  #   argv:
  #     - bash
  #     - '-lic'
  #     - 
  #   chdir: ~/ikamail
  # when: rails_db_version_result.rc != 0
