- name: Reload systemd
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: ansile_facts.service_mgr == "systemd"
  listen: system_reload_daemon

- name: Enforce SELinux
  become: true
  ansible.posix.selinux:
    policy: '{{ ansible_facts.selinux.targeted }}'
    state: enforcing
  when:
    - ansible_facts.selinux is defined
    - ansible_facts.selinux.status == "enabled"
  listen: system_enforce_selinux
