- name: Clone git repostiry nodokan
  ansible.builtin.git:
    repo: https://github.com/kue-ipc/nodokan.git
    dest: ~/nodokan
    version: main

- name: Run bundle install
  ansible.builtin.shell:
    cmd: bundle install
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true

- name: Run rails yarn:install
  ansible.builtin.shell:
    cmd: bin/rails yarn:install
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true

- name: Check rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails db:version
    executable: /bin/bash
    chdir: ~/nodokan
  ignore_errors: yes
  register: nodokan_rails_db_version_result

- name: Run rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails db:setup
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true
  when: nodokan_rails_db_version_result is failed

- name: Run rails db:migrate
  ansible.builtin.shell:
    cmd: bin/rails db:migrate
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true
  when: nodokan_rails_db_version_result is not failed

- name: Run rails radius:setup
  ansible.builtin.shell:
    cmd: bin/rails radius:setup
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true

- name: Run rails radius:setup for test
  ansible.builtin.shell:
    cmd: bin/rails radius:setup
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true
  environment:
    RAILS_ENV: test
