- name: Clone git repostiry nodokan
  ansible.builtin.git:
    repo: https://github.com/kue-ipc/nodokan.git
    dest: ~/nodokan
    version: main

# # テストに対しては未反映になる。
# - name: copy settings.local.yml
#   copy:
#     src: settings.local.yml
#     dest: '~/nodokan/config/{{ item }}'
#     mode: '0644'
#   loop:
#     - settings.local.yml

# - name: bundle config
#   command:
#     argv:
#       - bundle
#       - config
#       - set
#       - '{{ item.name }}'
#       - '{{ item.value }}'
#     chdir: ~/nodokan
#   loop:
#     - {name: path, value: vendor/bundle}

- name: Run bundle install
  ansible.builtin.shell:
    cmd: bundle install
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true

- name: Run rails yarn:install
  ansible.builtin.shell:
    cmd: bin/rails yarn:install
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true

# - name: check rails db version
#   command:
#     argv:
#       - bash
#       - '-lic'
#       - bin/rails db:version
#     chdir: ~/nodokan
#   ignore_errors: yes
#   register: rails_db_version_result

- name: Run rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails db:setup
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true

- name: Run rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails radius:setup
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true


- name: Run rails db:setup
  ansible.builtin.shell:
    cmd: bin/rails radius:setup
    executable: /bin/bash
    chdir: ~/nodokan
  changed_when: true
  environment:
    RAILS_ENV: test
