nodejs_name_src:
  pkg: nodejs
  snap: node
  mise: node
  anyenv: nodenv
nodejs_dep_pkgs_src:
  pkg: []
  snap: []
  mise:
    - libatomic1
  anyenv:
    - libatomic1
nodejs_bun_shell_block: |
  export BUN_INSTALL="$HOME/.bun"
  export PATH="$BUN_INSTALL/bin:$PATH"
