- name: Set gui imf
  ansible.builtin.set_fact:
    gui_imf: >-
      {{
        gui_default_imf[ansible_facts.distribution ~ ansible_facts.distribution_major_version]
          | default(gui_default_imf[ansible_facts.distribution]
            | default(gui_default_imf[ansible_facts.os_family]))
      }}
  when: gui_imf is not defined

- name: Set gui ime
  ansible.builtin.set_fact:
    gui_ime: >-
      {{
        gui_default_ime[ansible_facts.distribution ~ ansible_facts.distribution_major_version]
          | default(gui_default_ime[ansible_facts.distribution]
            | default(gui_default_ime[ansible_facts.os_family]))
      }}
  when: gui_ime is not defined

- name: Task install on app for IM
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ gui_imf }}-{{ gui_ime }}'

- name: Block im in bashrc for fcitx or fcitx5
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK im'
    block: |
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS="@im=fcitx"
      export DefaultIMModule=fcitx
      if [ $SHLVL = 1 ]; then
        (fcitx-autostart &>/dev/null &)
        xset -r 49 &>/dev/null
      fi
  when: gui_imf in ["fcitx", "fcitx5"]

- name: Block im in bashrc for other
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK im'
    block: |
      export GTK_IM_MODULE={{ gui_imf }}
      export QT_IM_MODULE={{ gui_imf }}
      export XMODIFIERS="@im={{ gui_imf }}"
      export DefaultIMModule={{ gui_imf }}
  when: gui_imf not in ["fcitx", "fcitx5"]
