- name: Task value on os for gui_desktop
  ansible.builtin.include_role:
    name: os
    tasks_from: value
  vars:
    os_value_os: '{{ gui_desktop_os }}'
  when: gui_desktop is not defined

- name: Set gui_desktop from os_value
  ansible.builtin.set_fact:
    gui_desktop: '{{ os_value }}'
  when: gui_desktop is not defined

- name: Task install on app for gui
  ansible.builtin.include_role:
    name: app
    tasks_from: install
  vars:
    app_install:
      name: '{{ gui_desktop }}'
      pkgs: '{{ gui_pkgs }}'

# https://github.com/microsoft/wslg/issues/960
- name: Stop and disable serivce for GDM
  become: true
  ansible.builtin.service:
    name: gdm
    enabled: false
    state: stopped
  when:
    - ansible_facts.virtualization_type == "wsl"
    - ansible_facts.distribution == "Ubuntu"
