proxy_loopback:
  - localhost
  - 127/8
  - ::1
proxy_linklocal:
  - .localdomain
  - 169.254.0.0/16
  - fe80::/10
proxy_private:
  - .local
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fc00::/7
