- name: Check pid 1 proccess
  ansible.builtin.command:
    cmd: ps -p 1 -o %c --no-headers
  changed_when: false
  register: system_run_ps_1

- name: Set system init
  ansible.builtin.set_fact:
    system_init: '{{ system_run_ps_1.stdout_lines | first | trim }}'
